name: Update README cards (self-hosted)

on:
  schedule:
    - cron: "17 2 * * *"   # daily at 02:17 UTC
  workflow_dispatch:       # allow manual runs
  push:
    paths:
      - ".github/workflows/update-readme-cards.yml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure assets folder
        run: mkdir -p assets

      - name: Fetch cards
        run: |
          curl -fsSL "https://github-readme-stats.vercel.app/api?username=renegade2k6&show_icons=true&theme=tokyonight&hide_border=true" -o assets/github-stats.svg
          curl -fsSL "https://github-readme-stats.vercel.app/api/top-langs/?username=renegade2k6&layout=compact&theme=tokyonight&hide_border=true" -o assets/top-langs.svg
          curl -fsSL "https://github-profile-trophy.vercel.app/?username=renegade2k6&theme=onedark&no-frame=true&margin-w=10&margin-h=10" -o assets/trophies.svg
          curl -fsSL "https://github-readme-streak-stats.herokuapp.com?user=renegade2k6&theme=tokyonight&hide_border=true" -o assets/streak.svg

      - name: Commit updated cards
        uses: EndBug/add-and-commit@v9
        with:
          add: "assets/*.svg"
          message: "chore: update README cards"
          default_author: github_actions
